stages:
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

deploy:
  stage: deploy
  before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh finn@172.105.169.195 "cd /srv/finn.lesueur.nz/ && git pull origin master --recurse-submodules && bash build-prod.sh && exit"
    - ssh finn@172.105.169.195 "cd /srv/dev.finn.lesueur.nz && git pull origin master --recurse-submodules && bash build-dev.sh && exit"
  only:
    - master
  artifacts:
    paths:
    - public
