stages:
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

deploy:
  stage: deploy
  before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh root@104.200.25.232 "cd /srv/finn.lesueur.nz/ && git checkout master && git pull origin master --recurse-submodules && exit"
    - ssh root@104.200.25.232 "cd /srv/finn.lesueur.nz/ && git submodule update --remote && exit"
    - ssh root@104.200.25.232 "cd /srv/finn.lesueur.nz/ && rm -rf public/ && exit"
    - ssh root@104.200.25.232 "cd /srv/finn.lesueur.nz/ && hugo && exit"
    - ssh root@104.200.25.232 "chown -R www-data /srv/finn.lesueur.nz/ && exit"
  only:
    - master
  artifacts:
    paths:
    - public
