baseurl                 = "https://finn.lesueur.nz"
contentdir              = "content"
layoutdir               = "layouts"
publishdir              = "/Users/finnlesueur/Sites/public.finn.lesueur.nz"
title                   = "Finn Le Sueur"
canonifyurls            = true
uglyurls                = false
staticDir               = ["static"]

DefaultContentLanguage  = "en"
LanguageCode            = "en"
theme                   = "hugo-finn"
metaDataFormat          = "yaml"
pygmentsUseClasses      = true
pygmentCodeFences       = true
enableGitInfo           = true

timeout                 = 600000

[markup.goldmark.renderer]
  unsafe=true

[Params]
  subtitle      = "Finn Le Sueur on the internet."
  logo          = "logo.png"
  favicon       = "favicon.ico"
  dateFormat    = "January 2, 2006"
  commit        = true
  rss           = true
  comments      = false
  mainSections  = ["posts", "photos", "reading"]
  imageHostingURL = "https://img.lesueur.nz"

[Author]
  name    = "Finn Le Sueur"
  email   = "finn@lesueur.nz"
  gitlab  = "Finnito"

[sitemap]
  changefreq  = "weekly"
  filename    = "sitemap.xml"
  priority    = 0.5

[mediaTypes]
[mediaTypes."text/gemini"]
  suffixes = ["gmi"]

[outputFormats]
[outputFormats.Gemini]
    baseName = "index"
    isPlainText = true
    isHTML = false
    mediaType = "text/gemini"
    protocol = "gemini://"
    permalinkable = true
    path = "gemini/"

[outputs]
  home = ["HTML", "RSS", "GEMINI"]
  page = ["HTML", "GEMINI"]
