baseurl                 = "https://finn.lesueur.nz"
contentdir              = "content"
layoutdir               = "layouts"
publishdir              = "public"
title                   = "Finn LeSueur on the internet"
canonifyurls            = true
uglyurls                = false
staticDir               = ["static"]

DefaultContentLanguage  = "en"
theme                   = "hugo-finn"
metaDataFormat          = "yaml"
pygmentsUseClasses      = true
pygmentCodeFences       = true

[Params]
  subtitle      = "Finn LeSueur on the internet."
  logo          = "logo.png"
  favicon       = "favicon.ico"
  dateFormat    = "January 2, 2006"
  commit        = true
  rss           = true
  comments      = false

[Author]
  name    = "Finn LeSueur"
  email   = "finn@lesueur.nz"
  gitlab  = "Finnito"

[menu]
  [[menu.main]]
    name    = "Home"
    url     = "/"
    weight  = 1

  [[menu.main]]
    name    = "All Posts"
    url     = "/posts/"
    weight  = 2

  [[menu.main]]
    name    = "Curriculum Vitae"
    url     = "/cv/"
    weight  = 3

  [[menu.main]]
    name    = "Me Elsewhere"
    url     = "/me-elsewhere/"
    weight  = 4

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5