baseurl                 = "https://finn.lesueur.nz"
contentdir              = "content"
layoutdir               = "layouts"
title                   = "Finn Le Sueur"
canonifyurls            = false
uglyurls                = false
staticDir               = ["static"]
DefaultContentLanguage  = "en"
LanguageCode            = "en"
theme                   = "hugo-finn"
metaDataFormat          = "yaml"
pygmentsUseClasses      = true
pygmentCodeFences       = true
enableGitInfo           = true
timeout                 = 600000

[_build]
  publishResources      = false

[markup.goldmark.renderer]
  unsafe                = true

[taxonomies]
  series                = 'series'

[Params]
  subtitle              = "Finn Le Sueur on the internet."
  logo                  = "logo.png"
  favicon               = "favicon.ico"
  dateFormat            = "January 2, 2006"
  commit                = true
  rss                   = true
  comments              = false
  mainSections          = ["posts", "photos", "reading"]
  imageHostingURL       = "https://imgproxy.lesueur.nz/insecure/"
  assetHostingURL       = "https://assets.lesueur.nz/blog/"

  [Params.Author]
    name                  = "Finn Le Sueur"
    email                 = "finn@lesueur.nz"
    gitlab                = "Finnito"

[sitemap]
  changefreq            = "weekly"
  filename              = "sitemap.xml"
  priority              = 0.5

[outputs]
  home                  = ["HTML", "RSS"]
  page                  = ["HTML"]
