name            = "Hugo-Finn"
license         = "MIT"
licenselink     = "https://gitlab.com/Finnito/hugo-finn/blob/master/LICENSE.md"
description     = "Very small, but pretty, fork of Hugo XMin theme."
homepage        = "https://finn.lesueur.nz"
tags            = ["minimal", "blog", "personal", "clean", "simple", "starter", "minimalist", "spartan"]
features        = ["blog"]
min_version     = "0.18"

[author]
  name      = "Finn LeSueur"
  homepage  = "https://science.lesueur.nz"
