name: Drafts
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy drafts to Linode
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: "cd /srv/drafts.finn.lesueur.nz/; su finn; git pull origin master; bash build-drafts.sh; exit;"
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.PASSWORD }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
