name: Deploy
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Linode
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: "cd /srv/finn.lesueur.nz/ && sudo -u finn git pull origin master && sudo -u finn bash build-prod.sh && exit;"
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.PASSWORD }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
